const question = document.querySelector('#question');
const choices = Array.from(document.querySelectorAll('.choice-text'));
const progressText = document.querySelector('#progressText');
const ScoreText = document.querySelector('#score');
const progressBarFull = document.querySelector('#progressBarFull');

let currentQuestion = {}
let acceptingAnswers = true
let score = 0
let questionCounter = 0
let availableQuestions =  []
let questions = [
    {
        question: 'Who wrote the Only Fools and Horses series?',
        choice1: 'Ben Elton',
        choice2: 'John Sullivan',
        choice3: 'Noah Hawley',
        choice4: 'Richard Curtis',
        answer: 2,
    },
    {
        question: 'What was the name of the very first episode?',
        choice1: 'Big Brother',
        choice2: 'Fatal Extraction',
        choice3: 'The Long Legs of the Law',
        choice4: 'Yesterday Never Comes',
        answer: 1,
    },
    {
        question: 'What tool did the madman in the episode Friday the 14th use on his victims?',
        choice1: 'A Knife',
        choice2: 'A Gun',
        choice3: 'A Axe',
        choice4: 'A Snooker Cue',
        answer: 3,
    },
    {
        question: 'Whose grandfathers ashes did Del try to dispose of in the episode Ashes to Ashes?',
        choice1: 'Triggers',
        choice2: 'Rodneys',
        choice3: 'Denzils',
        choice4: 'Raquels',
        answer: 1,
    },
    {  question: 'In what year was the very first epsiode show?',
        choice1: '1976',
        choice2: '1984',
        choice3: '1979',
        choice4: '1981',
        answer: 4,
    },
    {  question: 'What was the name of the episode that introduced Boycie?',
        choice1: 'Wanted',
         choice2: 'Go West Young Man',
        choice3: 'Happy Returns',
        choice4: 'From Prussia with Love',
        answer: 2,
},
    {  question: 'In the show, what was the name of the block of flats the Trotters lived in?',
    choice1: 'Nelson Mandela House',
    choice2: 'Bobby Moore House',
    choice3: 'Arthur Morgan House',
    choice4: 'William Wallace House',
    answer: 1,
},
    {  question: 'How many years seperated Del Boy and Rodney?',
    choice1: '11',
    choice2: '6',
    choice3: '8',
    choice4: '13',
    answer: 4,
},
{  question: 'Which three towns/cities are written on the side of Dels van?',
    choice1: 'Berlin - Warsaw - Peckham',
    choice2: 'New York - Madrid - Luton',
    choice3: 'New York - Paris - Peckham',
    choice4: 'Cape Town - London - Luton ',
    answer: 3,
},
{  question: 'How old was Rodney when his mum died?',
    choice1: '6',
    choice2: '1',
    choice3: '10',
    choice4: '4',
    answer: 1,
},
    {  question: 'Complete the title, Diamonds Are For...?',
    choice1: 'Heather',
    choice2: 'Mike',
    choice3: 'Forever',
    choice4: 'Sale',
    answer: 1,
},
    {  question: 'What was the name of Boycie and Marlenes son',
    choice1: 'Joseph',
    choice2: 'Tyler',
    choice3: 'Thomas',
    choice4: 'Dave',
    answer: 2,
},
    {  question: 'In the episode Sickness and Wealth it was revealed what was Boycies real christian name?',
    choice1: 'Chester',
    choice2: 'Charlton',
    choice3: 'Claudius',
    choice4: 'Aubrey',
    answer: 4,
},
    {  question: 'In the episode Dates, what did Trigger give as his occupation to the dating agency?',
    choice1: 'A Butcher',
    choice2: 'A Door to Door Salesman',
    choice3: 'A Bus Conductor',
    choice4: 'A Road Sweeper',
    answer: 3,
},
    {  question: 'Paul Barber (Denzil) played a role in which UK soap?',
    choice1: 'Brookside',
    choice2: 'Eastenders',
    choice3: 'Coronation Street',
    choice4: 'Crossroads',
    answer: 1,
},
    {  question: 'In the episode Cash and Curry how much did Del persuade the owner of the statue to sell it for?',
    choice1: '£2,000',
    choice2: '£5,000',
    choice3: '£800',
    choice4: '£55',
    answer: 1,
},
    {  question: 'If Del gave you a douce in bunce how much money would you have?',
    choice1: '£20',
    choice2: '£30',
    choice3: '£200',
    choice4: '£100',
    answer: 3,
},
    {  question: 'How many million viewers tuned in to watch Time On Our Hands, Christmas 1996?',
    choice1: '20 million',
    choice2: '16 million',
    choice3: '8 million',
    choice4: '25 million',
    answer: 4,
},
    {  question: 'In which episode did we first meet Uncle Albert?',
    choice1: 'To Hull and Back',
    choice2: 'Strained Relations',
    choice3: 'Video Nasty',
    choice4: 'A Royal Flush',
    answer: 2,
},
    {  question: 'Whos wife did the charcter Slater, used to be married to?',
    choice1: 'Del Boy',
    choice2: 'Rodney',
    choice3: 'Boycie',
    choice4: 'Mike',
    answer: 1,
},
    {  question: 'In the epsiode The Second Time Around, Del claimed that when he was young, girls would leave their boyfriends for a bloke who had a faster what?',
    choice1: 'Vespa',
    choice2: 'Mouth',
    choice3: 'Bicycle',
    choice4: 'Transit Van',
    answer: 1,
},
    {  question: 'What type of car did Rodney buy Del in the epsiode Time on Our Hands?',
    choice1: 'A Bentley',
    choice2: 'A Mercedes',
    choice3: 'A Rolls-Royce',
    choice4: 'A Honda Civic',
    answer: 3,
},
    {  question: 'In the epsiode It Never Rains, What war was being fought the last time Grandad visited Spain?',
    choice1: 'The Vietnam War',
    choice2: 'The Korea War',
    choice3: 'The Second World War',
    choice4: 'The Spanish Civil War',
    answer: 4,
},
    {  question: 'What was Cassandras maiden name?',
    choice1: 'Dyer',
    choice2: 'Wallace',
    choice3: 'Shipman',
    choice4: 'Parry',
    answer: 4,
},
    {  question: 'In the episode A Touch Of Glass, what did Del purchase a consignment of at the auction?',
    choice1: 'Broken China Plates',
    choice2: 'Musical Cats',
    choice3: 'Tom Jones Vinyls',
    choice4: 'Alarm Clocks',
    answer: 2,
},
    {  question: 'What was the title of the first episode of Series 4?',
    choice1: 'Happy Returns',
    choice2: 'Whos A Pretty Boy',
    choice3: 'Hole In One',
    choice4: 'The Miracle of Peckham',
    answer: 1,
},
    {  question: 'What is the name of the episode in which the Trotters spend the night inside a supermarket?',
    choice1: 'Tea For Three',
    choice2: 'The Longest Night',
    choice3: 'A Royal Flush',
    choice4: 'Dates',
    answer: 2,
},
    {  question: 'In the episode Big Brother, how did Rodney think Trigger got his name?',
    choice1: 'Rodney thought he looked like a horse',
    choice2: 'Rodney thought he was slow',
    choice3: 'Rodney thought he was a jockey',
    choice4: 'Rodney thought he carried a gun',
    answer: 4,
},
    {  question: 'In the episode Friday The 14th, where in England was the cottage located in which the Trotters were going to stay?',
    choice1: 'The Yorkshire Dales',
    choice2: 'The Lake District',
    choice3: 'Cornwall',
    choice4: 'Somerset',
    answer: 3,
},
    {  question: 'In which episode were we first introduced to Del and Rodneys father?',
    choice1: 'Watching The Girls Go By',
    choice2: 'Yuppy Love',
    choice3: 'Thicker Than Water',
    choice4: 'Homesick',
    answer: 3,
},
    {  question: 'What type of pie did Auntie make for the Trotters in the episode The Second Time Around?',
    choice1: 'Shepherds Pie',
    choice2: 'Chicken & Mushroom Pie',
    choice3: 'Veggie Pie',
    choice4: 'Steak & Ale',
    answer: 1,
},
    {  question: 'In the episode A Touch of Glass, which formula 1 racing team did Del claim he used to drive for?',
    choice1: 'Volvo',
    choice2: 'The John Player Special Team',
    choice3: 'Peckham Force',
    choice4: 'Royal Mail',
    answer: 2,
},
    {  question: 'In the episode The Second Time Around, what did Del claim that most of Rodneys dates arrived at the flat by?',
    choice1: 'School Bus',
    choice2: 'Three Wheel Car',
    choice3: 'Skateboard',
    choice4: 'Taxi',
    answer: 3,
},
    {  question: 'In the episode May The Force Be With You, what stolen item did Slater ask Trigger about?',
    choice1: 'A 12 Piece Dinner Set',
    choice2: 'A Electric Fireplace',
    choice3: 'A Microwave',
    choice4: 'A Collection Of Valuable Paintings',
    answer: 3,
},
    {  question: 'Complete Uncle Alberts famous line, During the ......?',
    choice1: 'Great Depression',
    choice2: 'War',
    choice3: 'Middle Ages',
    choice4: 'News',
    answer: 2,
},
{  question: 'In the episode The Second Time Around, what did Trigger tell Del that Paulines ex-husband had died of?',
    choice1: 'Food Poisoning',
    choice2: 'Pneumonia',
    choice3: 'Whooping Cough',
    choice4: 'Heat Stroke',
    answer: 1,
},
{  question: 'In the episode Healthy competition, where did Del say the girl that Micky Pearce had met on holiday came from?',
    choice1: 'Brixton',
    choice2: 'Brazil',
    choice3: 'Sweden',
    choice4: 'Romania',
    answer: 3,
},
{  question: 'In which episode did the Driscoll brothers break Mickey Pearces arm?',
    choice1: 'The Russians Are Coming',
    choice2: 'Little Problems',
    choice3: 'A Slow Bus To Chingford',
    choice4: 'Healthy Competition',
    answer: 2,
},
{  question: 'In which series were we first introduced to Mickey Pearce?',
    choice1: 'Series 2',
    choice2: 'Series 5',
    choice3: 'Series 2',
    choice4: 'Series 3',
    answer: 4,
},
{  question: 'What was Mickey Pearces most distinct item of clothing?',
    choice1: 'His Hat',
    choice2: 'His Glasses',
    choice3: 'His Coat',
    choice4: 'His Backpack',
    answer: 1,
},
{  question: 'Which epsiode were we first introduced to the character Denzil?',
    choice1: 'Whos A Pretty Boy',
    choice2: 'May The Force Be With You',
    choice3: 'Its Only Rock and Roll',
    choice4: 'Sleeping Dogs Lie',
    answer: 1,
},
{  question: 'What was the name of Denzils wife?',
    choice1: 'Sarah',
    choice2: 'Shirley',
    choice3: 'Ada',
    choice4: 'Corrine',
    answer: 4,
},
{  question: 'When Del agreed to do the catering for Denzils wedding, what type of cake did he end up supplying?',
    choice1: 'A Red Velvet',
    choice2: 'A Jam Sponge',
    choice3: 'A Melted Ice Cream Cake',
    choice4: 'A Chocolate Cake',
    answer: 2,
},
{  question: 'What was Uncle Alberts favourite drink?',
    choice1: 'Red Wine',
    choice2: 'Rum',
    choice3: 'Tia Maria',
    choice4: 'Guinness',
    answer: 2,
},
{  question: 'Who played the character Uncle Albert?',
    choice1: 'Buster Merryfield',
    choice2: 'Buster Douglas',
    choice3: 'Buster Cherryfield',
    choice4: 'Buster Hatton',
    answer: 1,
},
{  question: 'How many televisions would Grandad watch at the same time?',
    choice1: '1',
    choice2: '4',
    choice3: '3',
    choice4: '5',
    answer: 3,
},
{  question: 'How many series did Grandad appear in?',
    choice1: '6',
    choice2: '3',
    choice3: '4',
    choice4: '1',
    answer: 2,
},
{  question: 'What was the name of Del and Rodneys mum?',
    choice1: 'Pauline',
    choice2: 'Kris',
    choice3: 'Jennie',
    choice4: 'Joanie',
    answer: 4,
},
{  question: 'When Del got Rodney his job as a Trainee NSO, what did Del say the letters NSO stand for?',
    choice1: 'Nocturnal Secuirty Officer',
    choice2: 'New Student Officer',
    choice3: 'Normal Service Officer',
    choice4: 'Never Surrender Officer',
    answer: 1,
},
{  question: 'What is the surname of Dels friend Monkey?',
    choice1: 'Robinson',
    choice2: 'Harris',
    choice3: 'Wilson',
    choice4: 'Charles',
    answer: 2,
},
{  question: 'What occupation did Cassandra have when she first met Rodney?',
    choice1: 'Bank Clerk',
    choice2: 'Till Girl',
    choice3: 'Police Officer',
    choice4: 'Journalist',
    answer: 1,
},
{  question: 'Who did Cassandra go on a date with before Rodney?',
    choice1: 'Mickey Pearce',
    choice2: 'Denzil',
    choice3: 'Mike',
    choice4: 'None of the Above',
    answer: 4,
},
{  question: 'What was Mikes surname?',
    choice1: 'Carter',
    choice2: 'Fisher',
    choice3: 'Stevens',
    choice4: 'Roberts',
    answer: 2,
},
{  question: 'According to Del, Boycie had more front than which English seaside resort?',
    choice1: 'Margate',
    choice2: 'Dover',
    choice3: 'Brighton',
    choice4: 'Exeter',
    answer: 3,
},
{  question: 'Which Scandinavian country did Del tell Mr Chin led the world in paint technology?',
    choice1: 'Norway',
    choice2: 'Sweden',
    choice3: 'Denmark',
    choice4: 'Greece',
    answer: 1,
},
{  question: 'In the epsiode Homesick, where in France did Rodney suggest they take Grandad to be cured of his illness?',
    choice1: 'Lourdes',
    choice2: 'Paris',
    choice3: 'Lyon',
    choice4: 'Bordeaux',
    answer: 1,
},
{  question: 'When Rodney asked Irene out, he assumed she would say no and he mentioned which two exscuses that she might use?',
    choice1: 'Washing her hair and seeing whats on the television',
    choice2: 'Washing her hair and mending her bike',
    choice3: 'Taking her son to the park and watering her plants',
    choice4: 'Watering her plants and feeding the cat',
    answer: 2,
},
{  question: 'When the Trotters painted the Chinese, in the episode Yellow Peril, where did Trigger get the paint from?',
    choice1: 'A paint store',
    choice2: 'His dads lockup',
    choice3: 'He found it',
    choice4: 'A Storage shed at a railway station',
    answer: 4,
},
{  question: 'In the epsiode Video Nasty, which two mates brought Del back from the hospital to the flat',
    choice1: 'Slater and Monkey Harris',
    choice2: 'Mike and Boycie',
    choice3: 'Mike and Trigger',
    choice4: 'Denzil and Trigger',
    answer: 3,
},
{  question: 'When Del thought that Debbie might be his daughter, why were Trigger and Rodney so convinced that she couldnt be?',
    choice1: 'Because she was a pretty girl',
    choice2: 'Because she was smart',
    choice3: 'Because the dates didnt work out',
    choice4: 'Because was kind and soft spoken',
    answer: 1,
},
{  question: 'How many times in the epsiode Strained Relations, did Albert say he had been aboard a ship that had been dive bombed in peacetime?',
    choice1: '11',
    choice2: '4',
    choice3: '2',
    choice4: '1',
    answer: 3,
},
{  question: 'What did Trigger always call Rodney?',
    choice1: 'Mate',
    choice2: 'Dave',
    choice3: 'Larry',
    choice4: 'Kid',
    answer: 2,
},
{  question: 'In the episode Tea For Three, what relationship was Trigger to the girl that Rodney and Del were competing for?',
    choice1: 'Uncle',
    choice2: 'Brother',
    choice3: 'Godfather',
    choice4: 'Neighbour',
    answer: 1,
},
{  question: 'What was Triggers occupation?',
    choice1: 'Bus Driver',
    choice2: 'Lawyer',
    choice3: 'Road Sweeper',
    choice4: 'Funeral Director',
    answer: 3,
},
{  question: 'What was the name of Dels old friend who visited and was now living in Australia?',
    choice1: 'Jumbo Cummings',
    choice2: 'Jumbo Simpkins',
    choice3: 'Jumbo Shrimp',
    choice4: 'Jumbo Mills',
    answer: 4,
},
{  question: 'What type of stall did Del and his old mate Jumbo have before Jumbo left?',
    choice1: 'A Fruit & Veg Stall',
    choice2: 'A Fish Stall',
    choice3: 'A Cleaning Equipment Stall',
    choice4: 'A Vinyl Record Stall',
    answer: 2,
},
{  question: 'When Del and Rodney planned to emigrate to Australia, Rodneys visa application was rejected, why?',
    choice1: 'He had a criminal record',
    choice2: 'He forgot to pay the application fee',
    choice3: 'A spelling mistake',
    choice4: 'He sent it to the wrong address',
    answer: 1,
},
{  question: 'When negotiatng a new job offer for Rodney what did Del think a CV meant?',
    choice1: 'Corrected Viscosity',
    choice2: 'Car Vehicle',
    choice3: 'Citroen (CV model)',
    choice4: 'None of the above',
    answer: 3,
},
{  question: 'When Trigger complained about the taste of the beer in the Nags Head, which river did Uncle Albert say the beer tasted like?',
    choice1: 'The River Nile',
    choice2: 'The River Danube',
    choice3: 'The Amazon River',
    choice4: 'The Mississippi River',
    answer: 1,
},
{  question: 'When attending a wedding in the episode a Frogs Legacy, what present did Del buy for the happy couple?',
    choice1: 'A His and Hers Hairdryer',
    choice2: 'A Dinner Set',
    choice3: 'Laundry Powder',
    choice4: 'A Teapot',
    answer: 2,
},
{  question: 'How old was Uncle Albert when he first joined the navy?',
    choice1: '14',
    choice2: '18',
    choice3: '22',
    choice4: '17',
    answer: 4,
},
{  question: 'When meeting with the people from a Dating agency, Del promised that the lucky girl on his blind date would be guaranteed what?',
    choice1: 'A ride in his three wheel van',
    choice2: 'Steak',
    choice3: 'Bottle of fiz',
    choice4: 'The greatest night of her life',
    answer: 2,
},
{  question: 'Can you complete the title of Rodneys painting - Marble Arch at ....',
    choice1: 'Dawn',
    choice2: 'Night',
    choice3: 'First Day',
    choice4: 'Light',
    answer: 1,
},
{  question: 'When Rodney won a painting competition the prize was a holiday to where?',
    choice1: 'Istanbul',
    choice2: 'Crete',
    choice3: 'Mallorca',
    choice4: 'Margate',
    answer: 3,
},
{  question: 'In the epsiode The Unlucky Winner Is, what was the name of the gang that Rodney was made an honorary member of?',
    choice1: 'The Winners Gang',
    choice2: 'The Groovy Gang',
    choice3: 'The Holiday Gang',
    choice4: 'The No Girls Allowed Gang',
    answer: 2,
},
{  question: 'What was the name of the club in the beginning of the epsiode Chain Gang?',
    choice1: 'The Kit Kat Club',
    choice2: 'The Nighty Night Club',
    choice3: 'The Twenty Four Club',
    choice4: 'The One Eleven Club',
    answer: 4,
},
{  question: 'Which Simply Red song was playing at Rodneys wedding reception?',
    choice1: 'Holding Back The Years',
    choice2: 'Fairground',
    choice3: 'If You Dont Know Me By Now',
    choice4: 'You Make Me Feel Brand New',
    answer: 1,
},
{  question: 'Which seaside resort was the setting for the episode Jolly Boys Outing?',
    choice1: 'Brighton',
    choice2: 'Margate',
    choice3: 'Llandudno',
    choice4: 'Marbella',
    answer: 2,
},
{  question: 'What was the name of the hotel that Del, Rodney, and Uncle Albert stayed in during their outing to Maragte?', 
    choice1: 'Margate Central',
    choice2: 'St Georges Hotel',
    choice3: 'The Casa Hotel',
    choice4: 'The Villa Bella',
    answer: 4,
},
{  question: 'What is Del Boys middle name?',
    choice1: 'Churchill',
    choice2: 'George',
    choice3: 'Edward',
    choice4: 'Charles',
    answer: 3,
},
{  question: 'When attempting to do his part for the welcome dinner for Raquels parents, how did Uncle Albert mess up the gravy?',
    choice1: 'He threw away thinking it was off',
    choice2: 'He mixed the gravy with Washing up Liquid',
    choice3: 'He used coffee granuals by mistake',
    choice4: 'None of the above',
    answer: 3,
},
{  question: 'What did Del name the house that he brought from his share of the money from the sale of the watch?',
    choice1: 'Trotter Manor',
    choice2: 'House Of Trotter',
    choice3: 'Trotter Villa',
    choice4: 'Sunrise Manor',
    answer: 1,
},
{  question: 'In the epsiode Whos A Pretty Boy, how much did Grandad pay for the canary?',
    choice1: '£5',
    choice2: '£30',
    choice3: '£15',
    choice4: '£45',
    answer: 4,
},
{  question: 'What was Uncle Alberts full name?',
    choice1: 'Albert Reginald Trotter',
    choice2: 'Albert Gladstone Trotter',
    choice3: 'Albert Rodney Trotter',
    choice4: 'Albert Winston Trotter',
    answer: 2,
},
{  question: 'What is Rodneys middle name?',
    choice1: 'Charlton',
    choice2: 'John',
    choice3: 'Teddy',
    choice4: 'Derrick',
    answer: 1,
},
{  question: 'In the episode Heroes and Villians, what England football song did Del and Rodney sing when Cassandra announced her pregancy ?',
    choice1: 'Were On The Ball',
    choice2: 'World In Motion',
    choice3: 'Three Lions',
    choice4: 'Vindaloo',
    answer: 3,
},
{  question: 'What forest did Uncle Alberts beard remind Rodney of?',
    choice1: 'Glasfynydd Forest',
    choice2: 'Dartmoor Forest',
    choice3: 'Sherwood Forest',
    choice4: 'Epping Forest',
    answer: 4,
},
{  question: 'In the epsiode The Second Time Around, what did Pauline hide from Grandad',
    choice1: 'His False Teeth',
    choice2: 'His Whiskey',
    choice3: 'His Hat',
    choice4: 'His Watch',
    answer: 1,
},
{  question: 'In the epsiode Ashes To Ashes, Trigger said he was going on holiday to somewhere sunny with lots of beaches, where was he going?',
    choice1: 'Spain',
    choice2: 'Jamaica',
    choice3: 'Ireland',
    choice4: 'Scotland',
    answer: 3,
},
{  question: 'How many GCE O Levels did Rodney pass at school?',
    choice1: '0',
    choice2: '4',
    choice3: '7',
    choice4: '2',
    answer: 4,
},

]

const SCORE_POINTS = 100
const MAX_QUESTIONS = 25

startGame = () => {
    questionCounter = 0
    score = 0
    availableQuestions = [...questions] 
    getNewQuestion()
}

getNewQuestion = () => {
    if(availableQuestions.length === 0 || questionCounter === MAX_QUESTIONS) {
        localStorage.setItem('mostRecentScore', score)

        return window.location.assign('end.html')

    }

    questionCounter++
    progressText.innerText = `Question ${questionCounter}/${MAX_QUESTIONS}`
    progressBarFull.style.width = `${(questionCounter/MAX_QUESTIONS) * 100}%`

    const questionsIndex = Math.floor(Math.random() * availableQuestions.length)
    currentQuestion = availableQuestions[questionsIndex]
    question.innerText = currentQuestion.question

    choices.forEach(choice => {
        const number = choice.dataset['number']
        choice.innerText = currentQuestion['choice' + number]
    })

    availableQuestions.splice(questionsIndex, 1)

    acceptingAnswers = true
}

choices.forEach(choice => {
    choice.addEventListener('click', e =>{
        if(!acceptingAnswers) return

        acceptingAnswers = false
        const selectedChoice = e.target
        const selectedAnswer = selectedChoice.dataset['number']

        let classToApply = selectedAnswer == currentQuestion.answer ? 'correct' : 'incorrect'

        if(classToApply === 'correct') {
            incrementScore(SCORE_POINTS)
        }

        selectedChoice.parentElement.classList.add(classToApply)

        setTimeout(() => {
            selectedChoice.parentElement.classList.remove(classToApply)
            getNewQuestion()
        }, 1000)


    })
})

incrementScore = num => {
    score +=num
    ScoreText.innerText = score
}

startGame()
